SportsStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components
{
    // CartSummaryViewComponent is a View Component responsible for rendering the cart summary.
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart _cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            _cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }
}

SportsStore/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Data.Repositories.Abstract;
using SportsStore.Models;

namespace SportsStore.Components;

// View component providing data for the navigation menu.
public class NavigationMenuViewComponent : ViewComponent
{
    private readonly IStoreRepository _repository;

    public NavigationMenuViewComponent(IStoreRepository repo)
    {
        _repository = repo;
    }

    // Method invoked when rendering the view component.
    public IViewComponentResult Invoke()
    {
        // Set the selected category in the ViewBag for use in the view.
        ViewBag.SelectedCategory = RouteData?.Values["category"] ?? string.Empty;

        // Retrieve and return a sorted list of distinct product categories.
        return View(
            _repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x)
        );
    }
}

SportsStore/Views/Shared/ProductSummary.cshtml
@model Product

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
            <span class="badge rounded-pill bg-primary text-white"
                  style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>

    <!-- Form for adding a product to the shopping cart. Each form is uniquely identified by the product's ID. -->
    <form id="@Model.ProductId" asp-page="/Cart" method="post">
        <!-- Hidden input to store the product ID. This is crucial for identifying the product being added to the cart. -->
        <input type="hidden" asp-for="ProductId"/>

        <!-- Hidden input to store the return URL. This allows users to return to the current page after adding to the cart. -->
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>

        <span class="card-text p-1">
            @Model.Description
            <button type="submit" class="btn btn-success btn-sm pull-right" style="float:right">
                Add To Cart
            </button>
        </span>
    </form>

</div>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>SportsStore</title>
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet"/>
</head>
<body>
<div class="bg-dark text-white p-2">
    <div class="container-fluid">
        <div class="row">
            <div class="col navbar-brand">SPORTS STORE</div>
            <div class="col-6 navbar-text text-end">
                <vc:cart-summary/>
            </div>
        </div>
    </div>
</div>
<div class="row m-1 p-1">
    <div id="categories" class="col-3">
        <vc:navigation-menu/>
    </div>
    <div class="col-9">
        @RenderBody()
    </div>
</div>
</body>
</html>