SportsStore/Models/Cart.cs
namespace SportsStore.Models;

// Represents a shopping cart containing a list of cart lines.
public class Cart
{
    public List<CartLine> Lines { get; set; } = new();

    public virtual void AddItem(Product product, int quantity = 1)
    {
        var line = Lines.FirstOrDefault(p => p.Product.ProductId == product.ProductId);

        if (line == null)
            Lines.Add(new CartLine
            {
                Product = product,
                Quantity = quantity
            });
        else
            line.Quantity += quantity;
    }

    public virtual void RemoveLine(Product product)
    {
        Lines.RemoveAll(l => l.Product.ProductId == product.ProductId);
    }

    public decimal ComputeTotalValue()
    {
        return Lines.Sum(e => e.Product.Price * e.Quantity);
    }

    public virtual void Clear()
    {
        Lines.Clear();
    }
}

// Represents a single line in the shopping cart, associating a product with its quantity.
public class CartLine
{
    public int CartLineId { get; set; }

    public Product Product { get; set; } = new();

    public int Quantity { get; set; }
}

SportsStore/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Data.Repositories.Abstract;
using SportsStore.Models;

namespace SportsStore.Controllers;

public class OrderController : Controller
{
    private readonly Cart _cart;
    private readonly IOrderRepository _repository;

    public OrderController(IOrderRepository repoService, Cart cartService)
    {
        _repository = repoService;
        _cart = cartService;
    }

    public ViewResult Checkout()
    {
        return View(new Order());
    }

    [HttpPost]
    public IActionResult Checkout(Order order)
    {
        if (_cart.Lines.Count == 0)
            ModelState.AddModelError("", "Sorry, your cart is empty!");

        // ModelState is a property of the Controller base class that provides access to the ModelStateDictionary object.
        if (!ModelState.IsValid)
            return View();

        // Used ToArray() to ensure that the reference to the cart lines is copied, rather than the lines themselves.
        order.Lines = _cart.Lines.ToArray();
        _repository.SaveOrder(order);

        _cart.Clear();
        return RedirectToPage("/Completed", new { orderId = order.OrderId });
    }
}

SportsStore/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SportsStore.Data.Repositories.Abstract;
using SportsStore.Models;

namespace SportsStore.Pages
{
    // CartModel class represents the Razor Page model for managing the shopping cart.
    public class CartModel : PageModel
    {
        private IStoreRepository _repository;

        // Constructor to initialize the model with a repository and the Cart service.
        public CartModel(IStoreRepository repo, Cart cartService)
        {
            _repository = repo;
            Cart = cartService;
        }

        public Cart Cart { get; set; }

        public string ReturnUrl { get; set; } = "/";

        // Handler for the HTTP GET request to the Cart page, allowing specification of a return URL.
        public void OnGet(string? returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        // Handler for the HTTP POST request to add a product to the cart.
        public IActionResult OnPost(long productId, string returnUrl)
        {
            var product = _repository.Products
                .FirstOrDefault(p => p.ProductId == productId);

            if (product != null) Cart.AddItem(product, 1);

            // Redirect to the current URL with specified route values.
            return RedirectToPage(new { returnUrl });
        }

        // Handler for the HTTP POST request to remove a product from the cart.
        public IActionResult OnPostRemove(long productId, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(cl =>
                cl.Product.ProductId == productId).Product);

            return RedirectToPage(new { returnUrl });
        }
    }
}

SportsStore/Pages/Completed.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SportsStore.Pages;

public class CompletedModel : PageModel
{
    public void OnGet()
    {
    }
}

SportsStore/Pages/Cart.cshtml
@page
@model CartModel

<h2>Your cart</h2>
<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th>Quantity</th>
        <th>Item</th>
        <th class="text-right">Price</th>
        <th class="text-right">Subtotal</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var line in Model?.Cart?.Lines ?? Enumerable.Empty<CartLine>())
    {
        <tr>
            <td class="text-center">@line.Quantity</td>
            <td class="text-left">@line.Product.Name</td>
            <td class="text-right">@line.Product.Price.ToString("c")</td>
            <td class="text-right">
                @((line.Quantity * line.Product.Price).ToString("c"))
            </td>
            <td class="text-center">
                <!-- Form for removing a product from the shopping cart. The form handles the "Remove" page handler. -->
                <form asp-page-handler="Remove" method="post">
                    <!-- Hidden input to store the product ID of the line being removed. -->
                    <input type="hidden" name="ProductId" value="@line.Product.ProductId"/>
                    <!-- Hidden input to store the return URL. -->
                    <input type="hidden" name="returnUrl" value="@Model?.ReturnUrl"/>
                    <button type="submit" class="btn btn-sm btn-danger">
                        Remove
                    </button>
                </form>

            </td>
        </tr>
    }
    </tbody>
    <tfoot>
    <tr>
        <td colspan="3" class="text-right">Total:</td>
        <td class="text-right">
            @Model?.Cart?.ComputeTotalValue().ToString("c")
        </td>
    </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model?.ReturnUrl">Continue shopping</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Order"> Checkout </a>
</div>

SportsStore/Pages/Completed.cshtml
@page

<div class="text-center">
    <h2>Thanks!</h2>
    
    <p>Thanks for placing order #@OrderId</p>
    
    <p>We'll ship your goods as soon as possible.</p>
    
    <a class="btn btn-primary" asp-controller="Home">Return to Store</a>
</div>

@functions {
    // BindProperty attribute for binding the OrderId property from the query string.
    // SupportsGet is set to true to allow binding from query parameters.
    [BindProperty(SupportsGet = true)]
    public string? OrderId { get; set; }
}

SportsStore/Pages/_CartLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>SportsStore</title>
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>
</head>
<body>
<div class="bg-dark text-white p-2">
    <span class="navbar-brand ml-2">SPORTS STORE</span>
</div>
<div class="m-1 p-1">
    @RenderBody()
</div>
</body>
</html>